Development
ialiev685/goit-markup-hw-06 pull request #2
Opened 2021-01-30 22:20 UTC by ialiev685

Добрый вечер! ДЗ № 6 выполнил.

2021-01-31 10:24 UTC, magom001 requested changes
нужны небольшие правки

2021-01-31 10:24 UTC, magom001 commented on icon/icon-send.svg
> +<svg width="24" height="24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M24 0L0 13.5l7.67 2.84L19.5 5.25l-8.998 12.14.007.002-.009-.002V24l4.301-5.018L20.251 21 24 0z" fill="#fff"/></svg>
все иконки нужно унести в symbol-defs

2021-01-31 10:24 UTC, magom001 commented on css/style.css
> +  margin-left: auto;
на кнопке курсор должен быть  pointer

2021-01-31 10:24 UTC, magom001 commented on css/style.css
> +  cursor: pointer;
Почему ты решил, что на текстовых полях должен быть такой курсор?

2021-01-31 10:24 UTC, magom001 commented on css/style.css
> +  margin-left: auto;
по клику появляется нежелательный outline

2021-01-31 21:48 UTC, ialiev685 commented on icon/icon-send.svg
> +<svg width="24" height="24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M24 0L0 13.5l7.67 2.84L19.5 5.25l-8.998 12.14.007.002-.009-.002V24l4.301-5.018L20.251 21 24 0z" fill="#fff"/></svg>
Унес.

2021-01-31 21:50 UTC, ialiev685 commented on css/style.css
> +  margin-left: auto;
Добавил, нежелательное убрал.

2021-01-31 21:52 UTC, ialiev685 commented on css/style.css
> +  cursor: pointer;
Убрал. Не всегда понятно, нужен или не нужен поинтер.

2021-02-01 18:28 UTC, magom001 requested changes
Починить инпут в футере.

2021-02-01 18:28 UTC, magom001 commented on css/style.css
> +  display: inline-block;
У тебя на фокус тут ничего не происходит с инпутом (не меняется цвет обводки). Сделай так же, как в форме. В идеале ты не должен писать отдельные стили для инпута в футере. У тебя должен быть компонент инпут, который одинаково работает, независимо от того, где он используется.

2021-02-01 20:05 UTC, ialiev685 commented on css/style.css
> +  display: inline-block;
Сделал. По поводу БЭМ, я понял что по нему надо в начале вырабатывать план, где какой элемент будет под общим классом  т.е. когда приступаешь к разработке сайта. Мы делаем этапами, поэтому все переделывать нет возможности(отсутствие времени).

2021-02-02 09:26 UTC, magom001 approved these changes

2021-02-05 19:58 UTC, merged